version: '3'

services:
    office-file-processor:
        container_name: office-file-processor
        image: leanda/office-file-processor:latest
        environment:
        - TZ=EST
        - OSDR_LOG_FOLDER=/logs
        - OSDR_TEMP_FILES_FOLDER=/temps
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
        volumes:
        - ${OSDR_TEMP_FILES_FOLDER}:/temps/
        - ${OSDR_LOG_FOLDER}:/logs/
        build:
            context: .
        ports:
        - 8987:8087
        networks:
        - osdr-net-ext
            
networks:
    osdr-net-ext:
        external:
            name: osdr-sys-net
